import fs from 'fs-extra';
import path from 'path';
import yaml from 'yaml';

export interface TemplateConfig {
  name: string;
  description: string;
  version: string;
  nodes: any[];
  edges: any[];
  contracts: any[];
  guardrails: any;
  context_schema?: any;
}

export class TemplateManager {
  private templatesDir: string;

  constructor(templatesDir?: string) {
    this.templatesDir = templatesDir || path.join(__dirname, '.');
  }

  /**
   * List available templates
   */
  async listTemplates(): Promise<string[]> {
    try {
      const files = await fs.readdir(this.templatesDir);
      return files
        .filter(file => file.endsWith('.yaml') || file.endsWith('.yml'))
        .map(file => path.basename(file, path.extname(file)));
    } catch (error) {
      throw new Error(`Failed to list templates: ${error}`);
    }
  }

  /**
   * Load a template by name
   */
  async loadTemplate(templateName: string): Promise<TemplateConfig> {
    try {
      const templatePath = path.join(this.templatesDir, `${templateName}.yaml`);
      
      if (!(await fs.pathExists(templatePath))) {
        throw new Error(`Template '${templateName}' not found`);
      }

      const content = await fs.readFile(templatePath, 'utf-8');
      const config = yaml.parse(content) as TemplateConfig;

      // Validate template structure
      this.validateTemplate(config);

      return config;
    } catch (error) {
      throw new Error(`Failed to load template '${templateName}': ${error}`);
    }
  }

  /**
   * Generate topology files from template
   */
  async generateFromTemplate(
    templateName: string,
    outputDir: string,
    options: {
      projectName?: string;
      language?: string;
      customizations?: Record<string, any>;
    } = {}
  ): Promise<void> {
    const template = await this.loadTemplate(templateName);
    const { projectName = 'topokit-project', language = 'typescript' } = options;

    // Ensure output directory exists
    await fs.ensureDir(outputDir);
    await fs.ensureDir(path.join(outputDir, 'contracts'));
    await fs.ensureDir(path.join(outputDir, 'eval'));

    // Generate nodes.yaml
    const nodesContent = this.generateNodesYaml(template, projectName);
    await fs.writeFile(path.join(outputDir, 'nodes.yaml'), nodesContent);

    // Generate edges.yaml
    const edgesContent = this.generateEdgesYaml(template, projectName);
    await fs.writeFile(path.join(outputDir, 'edges.yaml'), edgesContent);

    // Generate guardrails.yaml
    const guardrailsContent = this.generateGuardrailsYaml(template, projectName);
    await fs.writeFile(path.join(outputDir, 'guardrails.yaml'), guardrailsContent);

    // Generate contracts
    await this.generateContracts(template, outputDir, projectName);

    // Generate README
    const readmeContent = this.generateReadme(template, projectName, language);
    await fs.writeFile(path.join(outputDir, 'README.md'), readmeContent);

    // Generate sample evaluation test
    const evalContent = this.generateSampleEval(template, projectName);
    await fs.writeFile(path.join(outputDir, 'eval', 'sample_test.yaml'), evalContent);
  }

  /**
   * Validate template structure
   */
  private validateTemplate(config: TemplateConfig): void {
    const requiredFields = ['name', 'description', 'version', 'nodes', 'edges', 'contracts', 'guardrails'];
    
    for (const field of requiredFields) {
      if (!(field in config)) {
        throw new Error(`Template missing required field: ${field}`);
      }
    }

    if (!Array.isArray(config.nodes)) {
      throw new Error('Template nodes must be an array');
    }

    if (!Array.isArray(config.edges)) {
      throw new Error('Template edges must be an array');
    }

    if (!Array.isArray(config.contracts)) {
      throw new Error('Template contracts must be an array');
    }

    if (typeof config.guardrails !== 'object') {
      throw new Error('Template guardrails must be an object');
    }
  }

  /**
   * Generate nodes.yaml content
   */
  private generateNodesYaml(template: TemplateConfig, projectName: string): string {
    return `# TopoKit Nodes Configuration
# Generated by topokit-cli init --template=${template.name}
# Project: ${projectName}

${yaml.stringify({ nodes: template.nodes }, { indent: 2 })}`;
  }

  /**
   * Generate edges.yaml content
   */
  private generateEdgesYaml(template: TemplateConfig, projectName: string): string {
    return `# TopoKit Edges Configuration
# Generated by topokit-cli init --template=${template.name}
# Project: ${projectName}

${yaml.stringify({ edges: template.edges }, { indent: 2 })}`;
  }

  /**
   * Generate guardrails.yaml content
   */
  private generateGuardrailsYaml(template: TemplateConfig, projectName: string): string {
    return `# TopoKit Guardrails Configuration
# Generated by topokit-cli init --template=${template.name}
# Project: ${projectName}

${yaml.stringify(template.guardrails, { indent: 2 })}`;
  }

  /**
   * Generate contract files
   */
  private async generateContracts(template: TemplateConfig, outputDir: string, projectName: string): Promise<void> {
    const contractsDir = path.join(outputDir, 'contracts');
    
    for (const contract of template.contracts) {
      const contractContent = `# TopoKit Contract: ${contract.name}
# Generated by topokit-cli init --template=${template.name}
# Project: ${projectName}

${yaml.stringify(contract, { indent: 2 })}`;
      
      await fs.writeFile(path.join(contractsDir, `${contract.name}.yaml`), contractContent);
    }
  }

  /**
   * Generate README.md
   */
  private generateReadme(template: TemplateConfig, projectName: string, language: string): string {
    return `# ${projectName}

${template.description}

## Template: ${template.name} v${template.version}

This project was generated using the TopoKit CLI with the \`${template.name}\` template.

## Project Structure

\`\`\`
${projectName}/
├── nodes.yaml          # Node definitions
├── edges.yaml          # Edge definitions  
├── guardrails.yaml     # Guardrails configuration
├── contracts/          # Contract definitions
│   ${template.contracts.map(c => `├── ${c.name}.yaml`).join('\n│   ')}
├── eval/              # Evaluation tests
│   └── sample_test.yaml
└── README.md          # This file
\`\`\`

## Quick Start

1. **Validate the topology:**
   \`\`\`bash
   topokit-cli lint
   \`\`\`

2. **Generate a visualization:**
   \`\`\`bash
   topokit-cli graph
   \`\`\`

3. **Run evaluation tests:**
   \`\`\`bash
   topokit-cli eval
   \`\`\`

## Nodes

This topology contains ${template.nodes.length} nodes:

${template.nodes.map(node => `- **${node.id}** (${node.kind}): ${node.scope?.contracts?.join(', ') || 'No contracts'}`).join('\n')}

## Edges

This topology contains ${template.edges.length} edges:

${template.edges.map(edge => `- **${edge.id}**: ${edge.from} → ${edge.to}`).join('\n')}

## Contracts

This topology defines ${template.contracts.length} contracts:

${template.contracts.map(contract => `- **${contract.name}** v${contract.version}: ${contract.input_schema?.type || 'object'} → ${contract.output_schema?.type || 'object'}`).join('\n')}

## Development

### Prerequisites

- Node.js 18+
- Python 3.8+ (for core functionality)
- TopoKit CLI

### Installation

\`\`\`bash
# Install TopoKit CLI globally
npm install -g @topokit/cli

# Or use locally
npx @topokit/cli
\`\`\`

### Available Commands

- \`topokit-cli init\` - Initialize a new project
- \`topokit-cli lint\` - Validate topology configuration
- \`topokit-cli graph\` - Generate topology visualization
- \`topokit-cli eval\` - Run evaluation tests
- \`topokit-cli monitor\` - Monitor topology execution
- \`topokit-cli help\` - Show help information

## Configuration

### Guardrails

The topology includes comprehensive guardrails for:
- Determinism control
- Confidence gating
- Fallback strategies
- Content moderation
- Circuit breakers
- Human-in-the-loop gates

### Performance

- **Latency Budget**: ${template.nodes.map(n => n.slos?.latency_budget).filter(Boolean)[0] || 'Not specified'}
- **Schema Pass Rate**: ${template.nodes.map(n => n.slos?.schema_pass_rate).filter(Boolean)[0] || 'Not specified'}
- **Consistency Rate**: ${template.nodes.map(n => n.slos?.consistency_rate).filter(Boolean)[0] || 'Not specified'}

## Next Steps

1. Customize the topology configuration for your specific use case
2. Implement the actual node logic for your application
3. Add more evaluation tests in the \`eval/\` directory
4. Deploy and monitor your topology in production

## Support

- Documentation: https://topokit.dev/docs
- Issues: https://github.com/topokit/topokit/issues
- Community: https://discord.gg/topokit
`;
  }

  /**
   * Generate sample evaluation test
   */
  private generateSampleEval(template: TemplateConfig, projectName: string): string {
    return `# Sample Evaluation Test
# Generated by topokit-cli init --template=${template.name}
# Project: ${projectName}

name: "sample_test"
description: "Sample evaluation test for ${template.name} template"
version: "1.0.0"

test_cases:
  - name: "basic_functionality"
    description: "Test basic topology execution"
    input:
      query: "What is the capital of France?"
      context: ["Paris is the capital of France."]
    expected_output:
      answer: "Paris"
      confidence: 0.9
    timeout_ms: 10000

  - name: "error_handling"
    description: "Test error handling and fallback"
    input:
      query: ""
      context: []
    expected_output:
      error: true
    timeout_ms: 5000

  - name: "performance_test"
    description: "Test performance requirements"
    input:
      query: "What is the meaning of life?"
      context: ["The meaning of life is 42."]
    expected_output:
      answer: "42"
      confidence: 0.8
    timeout_ms: 5000
    performance_requirements:
      max_latency_ms: 3000
      min_confidence: 0.7

evaluation_metrics:
  - name: "accuracy"
    weight: 0.4
    threshold: 0.8
  - name: "confidence"
    weight: 0.3
    threshold: 0.7
  - name: "latency"
    weight: 0.2
    threshold: 5000
  - name: "consistency"
    weight: 0.1
    threshold: 0.9
`;
  }
}
